; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23026.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG129079 DB	'C:\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qmetatype.h'
	DB	00H
	ORG $+7
$SG129080 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG129081 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG130301 DB	'C:\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qmetatype.h'
	DB	00H
	ORG $+7
$SG130302 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG130303 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG128445 DB	'C:\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qmetatype.h'
	DB	00H
	ORG $+7
$SG128446 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG128447 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG131560 DB	'C:\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qmetatype.h'
	DB	00H
	ORG $+7
$SG131561 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG131562 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG130618 DB	'C:\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qmetatype.h'
	DB	00H
	ORG $+7
$SG130619 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG130620 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG128762 DB	'C:\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qmetatype.h'
	DB	00H
	ORG $+7
$SG128763 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG128764 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_UndoTableWidget@@3Uqt_meta_stringdata_UndoTableWidget_t@@B DD 0ffffffffH ; qt_meta_stringdata_UndoTableWidget
	DD	0fH
	DD	00H
	ORG $+4
	DQ	00000000000000a8H
	DD	0ffffffffH
	DD	012H
	DD	00H
	ORG $+4
	DQ	00000000000000a0H
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	000000000000009bH
	DD	0ffffffffH
	DD	05H
	DD	00H
	ORG $+4
	DQ	0000000000000084H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	0000000000000072H
	DD	0ffffffffH
	DD	011H
	DD	00H
	ORG $+4
	DQ	0000000000000065H
	DD	0ffffffffH
	DD	04H
	DD	00H
	ORG $+4
	DQ	000000000000005fH
	DB	'UndoTableWidget', 00H, 'showtablerightMenu', 00H, 00H, 'p'
	DB	'oint', 00H, 'slotUpdate', 00H, 'QTableWidgetItem*', 00H, 'ite'
	DB	'm', 00H
	ORG $+4
	ORG $+8
?qt_meta_data_UndoTableWidget@@3QBIB DD 07H		; qt_meta_data_UndoTableWidget
	DD	00H
	DD	00H
	DD	00H
	DD	02H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	01H
	DD	018H
	DD	02H
	DD	08H
	DD	04H
	DD	01H
	DD	01bH
	DD	02H
	DD	08H
	DD	02bH
	DD	019H
	DD	03H
	DD	02bH
	DD	080000005H
	DD	06H
	DD	00H
	ORG $+4
$SG129984 DB	'C:\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qmetatype.h'
	DB	00H
	ORG $+7
$SG129985 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG129986 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@UndoTableWidget@@UEBAPEBUQMetaObject@@XZ ; UndoTableWidget::metaObject
PUBLIC	?qt_metacast@UndoTableWidget@@UEAAPEAXPEBD@Z	; UndoTableWidget::qt_metacast
PUBLIC	?qt_metacall@UndoTableWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; UndoTableWidget::qt_metacall
PUBLIC	?qt_static_metacall@UndoTableWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; UndoTableWidget::qt_static_metacall
PUBLIC	?staticMetaObject@UndoTableWidget@@2UQMetaObject@@B ; UndoTableWidget::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QTableWidget@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QTableWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?showtablerightMenu@UndoTableWidget@@AEAAXVQPoint@@@Z:PROC ; UndoTableWidget::showtablerightMenu
EXTRN	?slotUpdate@UndoTableWidget@@AEAAXPEAVQTableWidgetItem@@@Z:PROC ; UndoTableWidget::slotUpdate
EXTRN	__imp_?staticMetaObject@QTableWidget@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@UndoTableWidget@@2UQMetaObject@@B DB 030H DUP (?) ; UndoTableWidget::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@UndoTableWidget@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@UndoTableWidget@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@UndoTableWidget@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@UndoTableWidget@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@UndoTableWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@UndoTableWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@UndoTableWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+133
	DD	imagerel $unwind$?qt_static_metacall@UndoTableWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@UndoTableWidget@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@UndoTableWidget@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@UndoTableWidget@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@UndoTableWidget@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@UndoTableWidget@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@UndoTableWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@UndoTableWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	06217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@UndoTableWidget@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@UndoTableWidget@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'UndoTableWidget::staticMetaObject'', COMDAT
; File h:\project_learn\redo_undo\redo_undo\generatedfiles\debug\moc_undotablewidget.cpp
; Line 87
	mov	rax, QWORD PTR __imp_?staticMetaObject@QTableWidget@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@UndoTableWidget@@2UQMetaObject@@B, rax
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_UndoTableWidget@@3Uqt_meta_stringdata_UndoTableWidget_t@@B
	mov	QWORD PTR ?staticMetaObject@UndoTableWidget@@2UQMetaObject@@B+8, rax
; Line 88
	lea	rax, OFFSET FLAT:?qt_meta_data_UndoTableWidget@@3QBIB
	mov	QWORD PTR ?staticMetaObject@UndoTableWidget@@2UQMetaObject@@B+16, rax
	lea	rax, OFFSET FLAT:?qt_static_metacall@UndoTableWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; UndoTableWidget::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@UndoTableWidget@@2UQMetaObject@@B+24, rax
	mov	QWORD PTR ?staticMetaObject@UndoTableWidget@@2UQMetaObject@@B+32, 0
	mov	QWORD PTR ?staticMetaObject@UndoTableWidget@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@UndoTableWidget@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'UndoTableWidget::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_t$1 = 40
_o$ = 64
_c$ = 72
_id$ = 80
_a$ = 88
?qt_static_metacall@UndoTableWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; UndoTableWidget::qt_static_metacall
; File h:\project_learn\redo_undo\redo_undo\generatedfiles\debug\moc_undotablewidget.cpp
; Line 74
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 75
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN4@qt_static_
; Line 76
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$1[rsp], rax
; Line 78
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN6@qt_static_
	jmp	SHORT $LN7@qt_static_
$LN5@qt_static_:
; Line 79
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rdx, QWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?showtablerightMenu@UndoTableWidget@@AEAAXVQPoint@@@Z ; UndoTableWidget::showtablerightMenu
	jmp	SHORT $LN2@qt_static_
$LN6@qt_static_:
; Line 80
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	rdx, QWORD PTR [rax]
	mov	rcx, QWORD PTR _t$1[rsp]
	call	?slotUpdate@UndoTableWidget@@AEAAXPEAVQTableWidgetItem@@@Z ; UndoTableWidget::slotUpdate
$LN7@qt_static_:
$LN2@qt_static_:
$LN4@qt_static_:
; Line 84
	add	rsp, 56					; 00000038H
	ret	0
?qt_static_metacall@UndoTableWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; UndoTableWidget::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@UndoTableWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; UndoTableWidget::qt_metacall
; File h:\project_learn\redo_undo\redo_undo\generatedfiles\debug\moc_undotablewidget.cpp
; Line 106
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 107
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QTableWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 108
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 109
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 110
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 111
	cmp	DWORD PTR _id$[rsp], 2
	jge	SHORT $LN5@qt_metacal
; Line 112
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@UndoTableWidget@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; UndoTableWidget::qt_static_metacall
$LN5@qt_metacal:
; Line 113
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 2
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 114
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 115
	cmp	DWORD PTR _id$[rsp], 2
	jge	SHORT $LN7@qt_metacal
; Line 116
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 117
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 2
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 119
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 120
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@UndoTableWidget@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; UndoTableWidget::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@UndoTableWidget@@UEAAPEAXPEBD@Z PROC	; UndoTableWidget::qt_metacast
; File h:\project_learn\redo_undo\redo_undo\generatedfiles\debug\moc_undotablewidget.cpp
; Line 98
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 99
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 100
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_UndoTableWidget@@3Uqt_meta_stringdata_UndoTableWidget_t@@B+168
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 101
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 102
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QTableWidget@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 103
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@UndoTableWidget@@UEAAPEAXPEBD@Z ENDP	; UndoTableWidget::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@UndoTableWidget@@UEBAPEBUQMetaObject@@XZ PROC ; UndoTableWidget::metaObject
; File h:\project_learn\redo_undo\redo_undo\generatedfiles\debug\moc_undotablewidget.cpp
; Line 93
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 94
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@UndoTableWidget@@2UQMetaObject@@B ; UndoTableWidget::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 95
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@UndoTableWidget@@UEBAPEBUQMetaObject@@XZ ENDP ; UndoTableWidget::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File c:\qt\qt5.8.0\5.8\msvc2015_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File h:\project_learn\redo_undo\redo_undo\generatedfiles\debug\moc_undotablewidget.cpp
; Line 123
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File h:\project_learn\redo_undo\redo_undo\generatedfiles\debug\moc_undotablewidget.cpp
; Line 123
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
