; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23026.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG129198 DB	'C:\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qmetatype.h'
	DB	00H
	ORG $+7
$SG129199 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG129200 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG128293 DB	'C:\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qmetatype.h'
	DB	00H
	ORG $+7
$SG128294 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG128295 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG130535 DB	'C:\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qmetatype.h'
	DB	00H
	ORG $+7
$SG130536 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG130537 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
?qt_meta_stringdata_questionlistdelegate@@3Uqt_meta_stringdata_questionlistdelegate_t@@B DD 0ffffffffH ; qt_meta_stringdata_questionlistdelegate
	DD	014H
	DD	00H
	ORG $+4
	DQ	0000000000000018H
	DB	'questionlistdelegate', 00H
	ORG $+3
?qt_meta_data_questionlistdelegate@@3QBIB DD 07H	; qt_meta_data_questionlistdelegate
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	ORG $+4
$SG129608 DB	'C:\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qmetatype.h'
	DB	00H
	ORG $+7
$SG129609 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG129610 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG127659 DB	'C:\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qmetatype.h'
	DB	00H
	ORG $+7
$SG127660 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG127661 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG127976 DB	'C:\Qt\Qt5.8.0\5.8\msvc2015_64\include\QtCore/qmetatype.h'
	DB	00H
	ORG $+7
$SG127977 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG127978 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@questionlistdelegate@@UEBAPEBUQMetaObject@@XZ ; questionlistdelegate::metaObject
PUBLIC	?qt_metacast@questionlistdelegate@@UEAAPEAXPEBD@Z ; questionlistdelegate::qt_metacast
PUBLIC	?qt_metacall@questionlistdelegate@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; questionlistdelegate::qt_metacall
PUBLIC	?qt_static_metacall@questionlistdelegate@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; questionlistdelegate::qt_static_metacall
PUBLIC	?staticMetaObject@questionlistdelegate@@2UQMetaObject@@B ; questionlistdelegate::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QItemDelegate@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QItemDelegate@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	__imp_?staticMetaObject@QItemDelegate@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@questionlistdelegate@@2UQMetaObject@@B DB 030H DUP (?) ; questionlistdelegate::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@questionlistdelegate@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@questionlistdelegate@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@questionlistdelegate@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@questionlistdelegate@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@questionlistdelegate@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN4
	DD	imagerel $LN4+74
	DD	imagerel $unwind$?qt_metacall@questionlistdelegate@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@questionlistdelegate@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@questionlistdelegate@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@questionlistdelegate@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@questionlistdelegate@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@questionlistdelegate@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@questionlistdelegate@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@questionlistdelegate@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@questionlistdelegate@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'questionlistdelegate::staticMetaObject'', COMDAT
; File h:\project_learn\redo_undo\redo_undo\generatedfiles\debug\moc_questionlistdelegate.cpp
; Line 66
	mov	rax, QWORD PTR __imp_?staticMetaObject@QItemDelegate@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@questionlistdelegate@@2UQMetaObject@@B, rax
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_questionlistdelegate@@3Uqt_meta_stringdata_questionlistdelegate_t@@B
	mov	QWORD PTR ?staticMetaObject@questionlistdelegate@@2UQMetaObject@@B+8, rax
; Line 67
	lea	rax, OFFSET FLAT:?qt_meta_data_questionlistdelegate@@3QBIB
	mov	QWORD PTR ?staticMetaObject@questionlistdelegate@@2UQMetaObject@@B+16, rax
	lea	rax, OFFSET FLAT:?qt_static_metacall@questionlistdelegate@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; questionlistdelegate::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@questionlistdelegate@@2UQMetaObject@@B+24, rax
	mov	QWORD PTR ?staticMetaObject@questionlistdelegate@@2UQMetaObject@@B+32, 0
	mov	QWORD PTR ?staticMetaObject@questionlistdelegate@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@questionlistdelegate@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'questionlistdelegate::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_o$ = 8
_c$ = 16
_id$ = 24
_a$ = 32
?qt_static_metacall@questionlistdelegate@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; questionlistdelegate::qt_static_metacall
; File h:\project_learn\redo_undo\redo_undo\generatedfiles\debug\moc_questionlistdelegate.cpp
; Line 58
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
; Line 63
	ret	0
?qt_static_metacall@questionlistdelegate@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; questionlistdelegate::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@questionlistdelegate@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; questionlistdelegate::qt_metacall
; File h:\project_learn\redo_undo\redo_undo\generatedfiles\debug\moc_questionlistdelegate.cpp
; Line 85
$LN4:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 86
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QItemDelegate@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 87
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 88
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 89
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 90
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@questionlistdelegate@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; questionlistdelegate::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@questionlistdelegate@@UEAAPEAXPEBD@Z PROC	; questionlistdelegate::qt_metacast
; File h:\project_learn\redo_undo\redo_undo\generatedfiles\debug\moc_questionlistdelegate.cpp
; Line 77
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 78
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 79
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_questionlistdelegate@@3Uqt_meta_stringdata_questionlistdelegate_t@@B+24
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 80
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 81
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QItemDelegate@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 82
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@questionlistdelegate@@UEAAPEAXPEBD@Z ENDP	; questionlistdelegate::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@questionlistdelegate@@UEBAPEBUQMetaObject@@XZ PROC ; questionlistdelegate::metaObject
; File h:\project_learn\redo_undo\redo_undo\generatedfiles\debug\moc_questionlistdelegate.cpp
; Line 72
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 73
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@questionlistdelegate@@2UQMetaObject@@B ; questionlistdelegate::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 74
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@questionlistdelegate@@UEBAPEBUQMetaObject@@XZ ENDP ; questionlistdelegate::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File c:\qt\qt5.8.0\5.8\msvc2015_64\include\qtcore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File h:\project_learn\redo_undo\redo_undo\generatedfiles\debug\moc_questionlistdelegate.cpp
; Line 93
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File h:\project_learn\redo_undo\redo_undo\generatedfiles\debug\moc_questionlistdelegate.cpp
; Line 93
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
